name: Python format and lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install development dependencies
        run: |
          poetry install
      - name: Check format and lint
        run: |
          poetry run ruff check
      - name: Test unit
        run: |
          poetry run pytest --cov
